build:
	python setup.py build
develop:
	python setup.py develop
inplace:
	python setup.py build_ext --inplace
#install:
#	python setup.py install
install:
	pip install -e .
clean:
	python setup.py clean
clean_all:
	rm -rf build/ dist/ *.so .cache/ \
  neighlist.egg-info/ \
  tests/*.pyc tests/*.xyz tests/__pycache__
